//
// Phase 5, step 6: fork-independent converter for .board / .game data assets.

package com.threerings.bang.tools.board;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import java.util.logging.Level;

import com.threerings.io.ObjectInputStream;
import com.threerings.io.ObjectOutputStream;

import com.jme.util.export.binary.BinaryImporter;

import com.threerings.bang.game.data.BangBoard;
import com.threerings.bang.game.data.BangConfig;
import com.threerings.bang.game.data.BoardData;
import com.threerings.bang.game.data.Criterion;
import com.threerings.bang.game.data.piece.Piece;
import com.threerings.bang.game.util.BoardFile;

/**
 * Converts the game's 165 {@code .board} files, 3 menu {@code town.board} backdrops, and 196
 * bounty {@code .game} files out of the vendored jME-fork {@code BinaryExporter} {@code Savable}
 * format and into a fork-independent <b>Narya stream</b> ({@code .nboard} / {@code .ngame}).
 *
 * <p>These 364 files have <b>no XML source</b> and so cannot be regenerated by the build the way
 * {@code model.dat} is; they need a one-time fork&rarr;non-fork conversion. The chosen target is
 * Narya streaming because every class involved is <b>already</b> a Narya {@link
 * com.threerings.io.Streamable} that crosses the wire to clients today:
 * {@link BangBoard} {@code extends SimpleStreamableObject}, {@link Piece} {@code implements
 * Streamable}, {@link com.threerings.bang.game.data.BoardData} {@code implements Streamable},
 * {@code BangConfig extends GameConfig} (a streamed {@code PlaceConfig}), and {@link Criterion}
 * {@code extends SimpleStreamableObject}. Re-using the wire encoding eliminates the fork
 * dependency entirely without inventing a new on-disk format and without a jME3 BinaryExporter.
 *
 * <p>The fork reader ({@link BoardFile#loadFrom} / {@link BinaryImporter}) is used ONLY here, to
 * read the legacy input. The runtime board/bounty load paths are not modified. Run once at
 * cutover, then this module is deleted with the rest of the fork.
 *
 * <p>On-disk Narya layout written by this tool:
 * <ul>
 *   <li><b>.nboard</b>: {@code UTF name; UTF creator; int players; boolean private;
 *       object scenarios(String[]); object board(BangBoard); object pieces(List&lt;Piece&gt;)}.
 *       (The {@code BoardFile} header fields, then the board graph. {@code dataHash} is derived,
 *       not stored, exactly as in the fork format.)</li>
 *   <li><b>.ngame</b>: {@code object config(BangConfig)} via a single {@code writeObject}.</li>
 * </ul>
 *
 * <p>Usage: {@code BoardConverter <input-root> <output-dir> [--boards|--games]}. Walks the input
 * root for {@code *.board} / {@code *.game}, writes converted files under the output dir
 * mirroring the relative path (extension swapped), round-trips every one, and prints a pass/fail
 * tally with any problem files named. Real input files are never modified or deleted. Runs fully
 * headless (a {@link com.jme.util.DummyDisplaySystem} is stood up so the fork reader works with no
 * GL context).
 */
public class BoardConverter
{
    public static void main (String[] args)
        throws Exception
    {
        if (args.length < 2) {
            System.err.println("Usage: BoardConverter <input-root> <output-dir> " +
                "[--boards|--games]");
            System.exit(1);
        }
        File inRoot = new File(args[0]).getAbsoluteFile();
        File outDir = new File(args[1]).getAbsoluteFile();
        boolean doBoards = true, doGames = true;
        if (args.length >= 3) {
            if (args[2].equals("--boards")) doGames = false;
            else if (args[2].equals("--games")) doBoards = false;
        }
        if (!inRoot.exists()) {
            System.err.println("Input root does not exist: " + inRoot);
            System.exit(1);
        }
        if (!outDir.isDirectory() && !outDir.mkdirs()) {
            System.err.println("Unable to create output dir: " + outDir);
            System.exit(1);
        }

        // the fork's Savable readers expect a display system to exist; stand up the headless
        // dummy exactly as tools/j3o-converter does. Quiet the fork's chatty logger.
        new com.jme.util.DummyDisplaySystem();
        com.jme.util.LoggingSystem.getLogger().setLevel(Level.WARNING);

        List<File> boards = new ArrayList<>(), games = new ArrayList<>();
        if (doBoards) collect(inRoot, ".board", boards);
        if (doGames) collect(inRoot, ".game", games);

        Tally tally = new Tally();
        System.out.println("Converting " + boards.size() + " board(s) and " + games.size() +
            " game(s) from " + inRoot);
        System.out.println();

        for (File f : boards) {
            convertBoard(f, inRoot, outDir, tally);
        }
        for (File f : games) {
            convertGame(f, inRoot, outDir, tally);
        }

        System.out.println();
        System.out.println("==== RESULT ====");
        System.out.println("boards: " + tally.boardsOk + " ok / " + tally.boardsFail + " fail" +
            " (of " + boards.size() + ")");
        System.out.println("games:  " + tally.gamesOk + " ok / " + tally.gamesFail + " fail" +
            " (of " + games.size() + ")");
        if (!tally.problems.isEmpty()) {
            System.out.println("problem files:");
            for (String p : tally.problems) {
                System.out.println("  " + p);
            }
        }
        System.exit(tally.problems.isEmpty() ? 0 : 2);
    }

    /** Reads one .board via the fork reader, writes a .nboard via Narya, and verifies. */
    protected static void convertBoard (File src, File inRoot, File outDir, Tally tally)
    {
        String rel = relPath(inRoot, src);
        try {
            BoardFile bf = BoardFile.loadFrom(src);
            // snapshot the fields we expect to survive the round trip
            BoardSummary before = BoardSummary.of(bf);

            byte[] enc = encodeBoard(bf);
            // round-trip in memory and only write the output file once it verifies, so a decode
            // failure or content mismatch never leaves a corrupt/stale .nboard on disk
            BoardSummary after = BoardSummary.of(decodeBoard(enc));
            String diff = before.diff(after);
            File out = mapOutput(outDir, rel, ".board", ".nboard");
            if (diff == null) {
                write(out, enc);
                tally.boardsOk++;
                System.out.println("OK   board " + rel + " -> " + out.getName() + "  " +
                    before.terse());
            } else {
                tally.boardsFail++;
                tally.problems.add("board " + rel + ": " + diff);
                System.out.println("FAIL board " + rel + ": " + diff);
            }
        } catch (Throwable t) {
            tally.boardsFail++;
            tally.problems.add("board " + rel + ": " + t);
            System.out.println("FAIL board " + rel + ": " + t);
            if (System.getProperty("convdebug") != null) t.printStackTrace();
        }
    }

    /** Reads one .game via the fork reader, writes a .ngame via Narya, and verifies. */
    protected static void convertGame (File src, File inRoot, File outDir, Tally tally)
    {
        String rel = relPath(inRoot, src);
        try {
            BangConfig cfg = (BangConfig)BinaryImporter.getInstance().load(src);
            GameSummary before = GameSummary.of(cfg);

            byte[] enc = encodeGame(cfg);
            // verify the in-memory round trip before writing, so a failure leaves no bad .ngame
            GameSummary after = GameSummary.of(decodeGame(enc));
            String diff = before.diff(after);
            File out = mapOutput(outDir, rel, ".game", ".ngame");
            if (diff == null) {
                write(out, enc);
                tally.gamesOk++;
                System.out.println("OK   game  " + rel + " -> " + out.getName() + "  " + before);
            } else {
                tally.gamesFail++;
                tally.problems.add("game " + rel + ": " + diff);
                System.out.println("FAIL game  " + rel + ": " + diff);
            }
        } catch (Throwable t) {
            tally.gamesFail++;
            tally.problems.add("game " + rel + ": " + t);
            System.out.println("FAIL game  " + rel + ": " + t);
            if (System.getProperty("convdebug") != null) t.printStackTrace();
        }
    }

    // ---- Narya encode/decode (the fork-independent target format) ----

    protected static byte[] encodeBoard (BoardFile bf)
        throws IOException
    {
        ByteArrayOutputStream bout = new ByteArrayOutputStream();
        ObjectOutputStream oout = new ObjectOutputStream(bout);
        oout.writeUTF(bf.name == null ? "" : bf.name);
        oout.writeUTF(bf.creator == null ? "" : bf.creator);
        oout.writeInt(bf.players);
        oout.writeBoolean(bf.privateBoard);
        oout.writeObject(bf.scenarios);
        // reuse the canonical {BangBoard, List<Piece>} wrapper rather than streaming board and
        // pieces as two separate contracts; BoardData is itself Narya-Streamable, so this keeps
        // one serialization shape that already matches the wire representation
        List<Piece> pieces = (bf.pieces == null) ?
            new ArrayList<Piece>() : new ArrayList<Piece>(bf.pieces);
        oout.writeObject(new BoardData(bf.board, pieces));
        oout.flush();
        return bout.toByteArray();
    }

    @SuppressWarnings("unchecked")
    protected static BoardFile decodeBoard (byte[] data)
        throws IOException, ClassNotFoundException
    {
        ObjectInputStream oin = new ObjectInputStream(new ByteArrayInputStream(data));
        BoardFile bf = new BoardFile();
        bf.name = oin.readUTF();
        bf.creator = oin.readUTF();
        bf.players = oin.readInt();
        bf.privateBoard = oin.readBoolean();
        bf.scenarios = (String[])oin.readObject();
        BoardData bd = (BoardData)oin.readObject();
        bf.board = bd.board;
        bf.pieces = bd.pieces;
        return bf;
    }

    protected static byte[] encodeGame (BangConfig cfg)
        throws IOException
    {
        ByteArrayOutputStream bout = new ByteArrayOutputStream();
        ObjectOutputStream oout = new ObjectOutputStream(bout);
        oout.writeObject(cfg);
        oout.flush();
        return bout.toByteArray();
    }

    protected static BangConfig decodeGame (byte[] data)
        throws IOException, ClassNotFoundException
    {
        ObjectInputStream oin = new ObjectInputStream(new ByteArrayInputStream(data));
        return (BangConfig)oin.readObject();
    }

    // ---- round-trip verification summaries ----

    /** The load-bearing fields of a board: name, dims, heightfield bytes, piece census. */
    protected record BoardSummary (
        String name, String creator, int players, boolean priv, String scenarios,
        int width, int height, int hfLen, int hfHash, String pieceCensus)
    {
        static BoardSummary of (BoardFile bf) {
            BangBoard b = bf.board;
            byte[] hf = (b == null) ? null : b.getHeightfield();
            String census = censusOf(bf.pieces);
            return new BoardSummary(
                nz(bf.name), nz(bf.creator), bf.players, bf.privateBoard,
                Arrays.toString(bf.scenarios),
                b == null ? -1 : b.getWidth(), b == null ? -1 : b.getHeight(),
                hf == null ? -1 : hf.length, hf == null ? 0 : Arrays.hashCode(hf),
                census);
        }
        String diff (BoardSummary o) {
            if (!Objects.equals(name, o.name)) return "name " + name + " != " + o.name;
            if (!Objects.equals(creator, o.creator)) return "creator mismatch";
            if (players != o.players) return "players " + players + " != " + o.players;
            if (priv != o.priv) return "private mismatch";
            if (!Objects.equals(scenarios, o.scenarios)) return "scenarios mismatch";
            if (width != o.width) return "width " + width + " != " + o.width;
            if (height != o.height) return "height " + height + " != " + o.height;
            if (hfLen != o.hfLen) return "heightfield len " + hfLen + " != " + o.hfLen;
            if (hfHash != o.hfHash) return "heightfield bytes differ";
            if (!Objects.equals(pieceCensus, o.pieceCensus))
                return "pieces " + pieceCensus + " != " + o.pieceCensus;
            return null;
        }
        String terse () {
            int n = pieceCensus.indexOf(':');
            String count = (n < 0) ? pieceCensus : pieceCensus.substring(0, n);
            return "[" + width + "x" + height + " hf=" + hfLen + "b pieces=" + count +
                " players=" + players + "]";
        }
    }

    /** A type+position census of the piece list, order-independent. */
    protected static String censusOf (List<Piece> pieces)
    {
        if (pieces == null) return "0";
        List<String> rows = new ArrayList<>();
        for (Piece p : pieces) {
            rows.add(p.getClass().getSimpleName() + "@" + p.x + "," + p.y +
                ":" + p.pieceId);
        }
        rows.sort(null);
        return pieces.size() + ":" + String.join(";", rows);
    }

    /** The load-bearing fields of a bounty config: rounds, scenarios, players, criteria. */
    protected record GameSummary (
        String type, String duration, String speed, int minWeight, boolean respawn,
        String rounds, String players, String criteria)
    {
        static GameSummary of (BangConfig c) {
            List<String> rs = new ArrayList<>();
            for (BangConfig.Round r : c.rounds) {
                rs.add(r.scenario + "|" + r.board + "|" + r.sdata);
            }
            List<String> ps = new ArrayList<>();
            for (BangConfig.Player p : c.plist) {
                ps.add(p.bigShot + "|" + Arrays.toString(p.units) + "|" +
                    Arrays.toString(p.cards) + "|" + p.startSpot + "|" + p.teamIdx +
                    "|" + p.skill);
            }
            List<String> cs = new ArrayList<>();
            for (Criterion cr : c.criteria) {
                cs.add(cr.getClass().getSimpleName() + ":" + cr.getDescription());
            }
            return new GameSummary(
                String.valueOf(c.type), String.valueOf(c.duration), String.valueOf(c.speed),
                c.minWeight, c.respawnUnits,
                rs.size() + ":" + String.join(";", rs),
                ps.size() + ":" + String.join(";", ps),
                cs.size() + ":" + String.join(";", cs));
        }
        String diff (GameSummary o) {
            if (!Objects.equals(type, o.type)) return "type " + type + " != " + o.type;
            if (!Objects.equals(duration, o.duration)) return "duration mismatch";
            if (!Objects.equals(speed, o.speed)) return "speed mismatch";
            if (minWeight != o.minWeight) return "minWeight mismatch";
            if (respawn != o.respawn) return "respawnUnits mismatch";
            if (!Objects.equals(rounds, o.rounds)) return "rounds " + rounds + " != " + o.rounds;
            if (!Objects.equals(players, o.players))
                return "players " + players + " != " + o.players;
            if (!Objects.equals(criteria, o.criteria))
                return "criteria " + criteria + " != " + o.criteria;
            return null;
        }
        @Override public String toString () {
            int nr = Integer.parseInt(rounds.substring(0, rounds.indexOf(':')));
            int np = Integer.parseInt(players.substring(0, players.indexOf(':')));
            int nc = Integer.parseInt(criteria.substring(0, criteria.indexOf(':')));
            return "[" + type + " rounds=" + nr + " players=" + np + " criteria=" + nc + "]";
        }
    }

    // ---- plumbing ----

    protected static void collect (File root, String ext, List<File> out)
    {
        if (root.isFile()) {
            if (root.getName().endsWith(ext)) out.add(root);
            return;
        }
        File[] kids = root.listFiles();
        if (kids == null) return;
        Arrays.sort(kids);
        for (File k : kids) collect(k, ext, out);
    }

    protected static String relPath (File root, File f)
    {
        String rp = root.toPath().relativize(f.toPath()).toString();
        return rp.isEmpty() ? f.getName() : rp;
    }

    protected static File mapOutput (File outDir, String rel, String fromExt, String toExt)
    {
        String mapped = rel.substring(0, rel.length() - fromExt.length()) + toExt;
        File out = new File(outDir, mapped);
        File parent = out.getParentFile();
        if (parent != null) parent.mkdirs();
        return out;
    }

    protected static void write (File out, byte[] data)
        throws IOException
    {
        try (FileOutputStream fos = new FileOutputStream(out)) {
            fos.write(data);
        }
    }

    protected static String nz (String s) { return s == null ? "" : s; }

    protected static final class Tally
    {
        int boardsOk, boardsFail, gamesOk, gamesFail;
        final List<String> problems = new ArrayList<>();
    }
}
